---
title: "Exploring PATH health facility data 2022"
#output: html_document
author: "Andy South @afrimapr"
date: "`r Sys.Date()`"
output: pdf_document
urlcolor: blue
always_allow_html: true
---

DRAFT

[Code for this document](https://github.com/afrimapr/senegal-healthsites-2022/blob/master/senegal-PATH-data-exlore.Rmd)   

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)

library(knitr)
library(tidyverse)
library(sf)
library(tmap)
library(mapview)

```


```{r read-data-path, include=FALSE}

# get local file data, can't share yet

# saved first sheet from xls as csv
# xls emailed from Mark 

folder <- "C:\\Users\\andy.south\\Google Drive\\afrimapr-gdrive\\Proposals\\2022-01-senegal-covidaction\\data\\"
filename <- "2022-02-senegal-structures.csv"
filename <- paste0(folder,filename)

#read in csv
#encoding fixes accents
dfpath <- read_csv(filename, locale=locale(encoding = "ISO-8859-1"))

# [1] "Région Médicale"      "District de Santé"    "Structure sanitaire"  "Type structure" 
# [5] "Autre type structure" "Statut"               "Latitude"             "Longitude"   


#convert column names to lowercase & remove any accents and spaces
names(dfpath) <- names(dfpath) %>% 
  #fix accents
  #str_conv(encoding = "ISO-8859-1") %>% 
  #remove accents
  stringi::stri_trans_general("Latin-ASCII") %>%
  #lower case
  str_to_lower() %>% 
  #replace spaces with _
  str_replace_all("\\s", "_")

table(dfpath$type_structure)
# autre   CMG    CS    HP    PS    RM 
#    36     1   100    12  1322    14 

# This legend appears in one file
# Type structure	
# PS	Poste de Santé
# DS	District de Sanitaire (Centre de santé)
# CS	Centre de Santé
# HP	Hopital
# RM	Région Médical
# autre	(Clinique, maternité, unité de vaccination, Dispensaire, etc;)

table(dfpath$statut) #priv-publ
# Communautaire    Prive conf    Prive laic        Public 
#             1            39            35          1410 


filename_districts <- "2022-02-senegal-health-districts.csv"
filename_districts <- paste0(folder,filename_districts)

dfdistricts <- read_csv(filename_districts, locale=locale(encoding = "ISO-8859-1"))
#remove last row which contains NA & breaks sf conversion later
dfdistricts <- filter(dfdistricts,!is.na(Polygones))

names(dfdistricts)
#[1] "Région Médicale"   "District de Santé" "Polygones" 
#get rid of accents, lowercase & replace spaces

names(dfdistricts) <- names(dfdistricts) %>% 
  #remove accents
  stringi::stri_trans_general("Latin-ASCII") %>%
  #lower case
  str_to_lower() %>% 
  #replace spaces with _
  str_replace_all("\\s", "_")


#sfdistricts <- st_as_sf(dfdistricts, wkt="Polygones")
# OGR: Unsupported geometry type
# Error in CPL_sfc_from_wkt(x) : OGR error

#this is what Geometry column looks like
# dfdistricts$Polygones[1]
# [1] "[[[[-17.4760,14.6985],[-17.4736,14.7306],[-17.4251,14.7447],[-17.4135,14.7329],[-17.4342,14.6821],[-17.4481,14.6978],[-17.4612,14.6781],[-17.4760,14.6985]]]]"

#nearly but not quite
#https://gis.stackexchange.com/questions/387069/how-to-read-csv-polygon-data-with-sf
#seems like I could remove []
#and add POLYGON 
#I got to this
#"LINESTRING ((-17.4760,14.6985,-17.4736,14.7306,-17.4251,14.7447,-17.4135,14.7329,-17.4342,14.6821,-17.4481,14.6978,-17.4612,14.6781,-17.4760,14.6985))"
#but still need to remove every other comma

#it should apparently look something like this, although this is 3D so has 4 items
#"POLYGON ((5 50 0 0.5, 20 50 0 0.5, 5 40 0 0.5, 20 40 0 0.5))"

dfdistricts <- dfdistricts %>%
                  #use temp X that later replace with comma
                  mutate(geo=str_replace_all(polygones,"\\],\\["," X ")) %>%   
                  mutate(geo=str_replace_all(geo,"\\[","")) %>% 
                  mutate(geo=str_replace_all(geo,"\\]","")) %>% 
                  mutate(geo=str_replace_all(geo,","," ")) %>% 
                  mutate(geo=str_replace_all(geo," X ",", ")) %>%   
                  mutate(geo=paste0("POLYGON ((",geo,"))"))  
                  #mutate(geo=paste0("LINESTRING ((",geo,"))"))  

sfdistricts <- st_as_sf(dfdistricts, wkt="geo", crs=4326)

#sfdistricts_sl <- filter(sfdistricts, `Région Médicale`=="RM Saint-Louis")
sfdistricts_sl <- filter(sfdistricts, region_medicale=="RM Saint-Louis")

# alas this seems to crash mapview
#mapview::mapview(sfdistricts_sl, zcol="District de Santé")

gg <- ggplot(sfdistricts_sl) +
    geom_sf() +
    theme_void() +
        geom_text(aes(label=district_de_sante, geometry=geo),
                     stat="sf_coordinates",
                     colour='darkgreen', size=4
                    )
    #geom_text( aes(label=district_de_sante))
    #geom_text( aes(label=`District de Santé`))

```

```{r make-geo-path, include=FALSE}

sfpath <- st_as_sf(dfpath, 
                  coords=c("longitude", "latitude"), 
                  na.fail = FALSE, crs=4326)

sfpath_sl <- filter(sfpath, region_medicale == "Saint Louis")

table(sfpath_sl$type_structure)
# autre   CMG    CS    HP    PS    RM 
#     2     1     6     1   110     1 

```


### Categories of PATH health facilities Saint Louis

```{r map-path-sl, eval=TRUE, fig.height=4}

#, fig.show='hold'

library(tmap)
library(afriadmin)

sfsen_adm0 <- afriadmin('senegal',level=0, plot=FALSE)
sfsen_adm1 <- afriadmin('senegal',level=1, plot=FALSE)

#map category types
tmap::tm_shape(filter(sfsen_adm1, shapeName=="Saint Louis")) +
    tm_borders("grey", lwd = .5) +
    tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
  
  tm_shape(sfpath_sl) +
    #tm_dots(shape=3, size = 0.15, col='red', border.lwd = 0.2) +
  

  #0square,1circle,2triangle,3+,4x,5diamond
  
    tm_symbols(shape="type_structure", col='red', shapes=c(0,1,3,2,4,5), size=0.1) +
  
    tm_layout(main.title='PATH health facilities Saint Louis 2022', main.title.size=1,
              legend.bg.color=TRUE, legend.position=c("center","BOTTOM"),
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) #main.title goes above map
   
#map statut (publ/priv)
tmap::tm_shape(filter(sfsen_adm1, shapeName=="Saint Louis")) +
    tm_borders("grey", lwd = .5) +
    tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
  
  tm_shape(sfpath_sl) +

  
  #0square,1circle,2triangle,3+,4x
  
    tm_symbols(shape="statut", col='darkgreen', shapes=c(0,1,2,3), size=0.1) +
  
    tm_layout(main.title='PATH health facilities Saint Louis 2022', main.title.size=1,
              legend.bg.color=TRUE, legend.position=c("center","BOTTOM"),
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) #main.title goes above map


```


### health districts from PATH data



